ZombiesZoneDefinition = ZombiesZoneDefinition or {};

-- total chance can be over 100% we don't care as we'll roll on the totalChance and not a 100 (unlike the specific outfits on top of this)
ZombiesZoneDefinition.Default = {};

--table.insert(ZombiesZoneDefinition.Default,{name = "FitnessInstructor", chance=20000});
table.insert(ZombiesZoneDefinition.Default,{name = "Generic01", chance=20});
table.insert(ZombiesZoneDefinition.Default,{name = "Generic02", chance=20});
table.insert(ZombiesZoneDefinition.Default,{name = "Generic03", chance=20});
table.insert(ZombiesZoneDefinition.Default,{name = "Generic_Skirt", gender="female", chance=20});
table.insert(ZombiesZoneDefinition.Default,{name = "Generic04", chance=20});
table.insert(ZombiesZoneDefinition.Default,{name = "Generic05", chance=20});
table.insert(ZombiesZoneDefinition.Default,{name = "Generic01", chance=20});
table.insert(ZombiesZoneDefinition.Default,{name = "Generic02", chance=20});
table.insert(ZombiesZoneDefinition.Default,{name = "Generic03", chance=20});
table.insert(ZombiesZoneDefinition.Default,{name = "Generic_Skirt", gender="female", chance=20});
table.insert(ZombiesZoneDefinition.Default,{name = "Generic04", chance=20});
table.insert(ZombiesZoneDefinition.Default,{name = "Generic05", chance=20});
table.insert(ZombiesZoneDefinition.Default,{name = "Generic01", chance=20});
table.insert(ZombiesZoneDefinition.Default,{name = "Generic02", chance=20});
table.insert(ZombiesZoneDefinition.Default,{name = "Generic03", chance=20});
table.insert(ZombiesZoneDefinition.Default,{name = "Generic_Skirt", gender="female", chance=20});
table.insert(ZombiesZoneDefinition.Default,{name = "Generic04", chance=20});
table.insert(ZombiesZoneDefinition.Default,{name = "Generic05", chance=20});
table.insert(ZombiesZoneDefinition.Default,{name = "Redneck", chance=5});
table.insert(ZombiesZoneDefinition.Default,{name = "Thug", chance=3});
table.insert(ZombiesZoneDefinition.Default,{name = "Hobbo", chance=2});
table.insert(ZombiesZoneDefinition.Default,{name = "Veteran", chance=5});
table.insert(ZombiesZoneDefinition.Default,{name = "Biker", chance=0.3});
table.insert(ZombiesZoneDefinition.Default,{name = "Cyclist", chance=0.5});
table.insert(ZombiesZoneDefinition.Default,{name = "DressLong", chance=3, gender="female"});
table.insert(ZombiesZoneDefinition.Default,{name = "DressNormal", chance=3, gender="female"});
table.insert(ZombiesZoneDefinition.Default,{name = "DressShort", chance=3, gender="female"});
table.insert(ZombiesZoneDefinition.Default,{name = "Golfer", chance=0.2});
table.insert(ZombiesZoneDefinition.Default,{name = "Young", chance=2});
table.insert(ZombiesZoneDefinition.Default,{name = "OfficeWorker", chance=2, gender="male"});
table.insert(ZombiesZoneDefinition.Default,{name = "OfficeWorkerSkirt", chance=2, gender="female"});
table.insert(ZombiesZoneDefinition.Default,{name = "Police", chance=0.5});
table.insert(ZombiesZoneDefinition.Default,{name = "PoliceState", chance=0.5});
table.insert(ZombiesZoneDefinition.Default,{name = "Ranger", chance=1});
table.insert(ZombiesZoneDefinition.Default,{name = "ConstructionWorker", chance=0.5, gender="male"});
table.insert(ZombiesZoneDefinition.Default,{name = "Farmer", chance=0.5});
table.insert(ZombiesZoneDefinition.Default,{name = "Student", chance=1});
table.insert(ZombiesZoneDefinition.Default,{name = "Foreman", chance=0.5, gender="male"});
table.insert(ZombiesZoneDefinition.Default,{name = "Bathrobe", chance=10, room="bathroom"});
table.insert(ZombiesZoneDefinition.Default,{name = "Naked", chance=10, room="bathroom"});
table.insert(ZombiesZoneDefinition.Default,{name = "Priest", chance=10, room="church", gender="male"});
table.insert(ZombiesZoneDefinition.Default,{name = "Bedroom", chance=10, room="bedroom"});
