require 'Items/SuburbsDistributions'

--////////////////////////////////////////////////// MALE-ITEMS

-- JUNK
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "Twigs");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 1);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "Newspaper");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.1);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "RippedSheetsDirty");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 1);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "RippedSheetsDirty");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 1);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "RippedSheetsDirty");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 1);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "CardDeck");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.01);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "Money");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 1);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "Money");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 1);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "Money");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 1);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "ElectronicsScrap");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.01);

-- GUNS
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "ShotgunShells");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "308Bullets");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "223Bullets");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "Bullets9mm");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "Bullets45");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "Bullets44");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "556Bullets");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.001);

-- MATERIALS
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "Rope");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "Wire");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "Twine");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "Paperclip");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "Tarp");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "Thread");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventorymale"].items, "Sheet");
table.insert(SuburbsDistributions["all"]["inventorymale"].items, 0.001);


--////////////////////////////////////////////////// FEMALE-ITEMS

-- JUNK
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "Twigs");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 1);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "Newspaper");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.1);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "RippedSheetsDirty");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 1);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "RippedSheetsDirty");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 1);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "RippedSheetsDirty");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 1);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "CardDeck");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.01);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "Money");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 1);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "Money");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 1);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "Money");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 1);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "ElectronicsScrap");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.01);

-- GUNS
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "ShotgunShells");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "308Bullets");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "223Bullets");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "Bullets9mm");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "Bullets45");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "Bullets44");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "556Bullets");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.001);

-- MATERIALS
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "Rope");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "Wire");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "Twine");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "Paperclip");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "Tarp");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "Thread");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.001);
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, "Sheet");
table.insert(SuburbsDistributions["all"]["inventoryfemale"].items, 0.001);